spring:
  cloud:
    config:
      import-check:
        enabled: false
  application:
    name: discovery-server
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

